In [23]:
import pandas as pd
import numpy as np

#Question 1 
data = {
    'ID': ['P001', 'P002', 'P003', 'P004', 'P005', 'P006'],
    'Pulse': [72, 85, 60, 78, 65, 90],
    'Systolic': [120, 135, 110, 125, 115, 140],
    'Diastolic': [80, 85, 70, 78, 75, 90],
    'Cholesterol': [190, 220, 180, 200, 210, 230],
    'AgeGroup': ['Adult', 'Adult', 'Senior', 'Adult', 'Senior', 'Adult']
}

df = pd.DataFrame(data)

#(a)  Pulse statstics 
mean_pulse = df['Pulse'].mean()
median_pulse = df['Pulse'].median()
std_pulse = df['Pulse'].std(ddof=0)
var_pulse = df['Pulse'].var()
min_pulse = df['Pulse'].min()
max_pulse = df['Pulse'].max()


print(f"Mean: {mean_pulse}")
print(f"Median: {median_pulse}")
print(f"Std deviation: {std_pulse}")
print(f"Variance: {var_pulse}")
print(f"Min: {min_pulse}")
print(f"Max: {max_pulse}")


Mean: 75.0
Median: 75.0
Std deviation: 10.55146119422961
Variance: 133.6
Min: 60
Max: 90


In [25]:
#(b) Covariance matrix and Eigen decomposition

numeric_df = df[['Pulse', 'Systolic', 'Diastolic', 'Cholesterol']]
cov_matrix = numeric_df.cov()
print("The covariance matrix:")
print(cov_matrix)

# Eigen decomposition
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)
print(f"Eigen Values: {eigenvalues}")
print("Eigen Vectors:")
print(eigenvectors)


The covariance matrix:
             Pulse    Systolic   Diastolic  Cholesterol
Pulse        133.6  133.000000   78.800000        176.0
Systolic     133.0  134.166667   79.666667        185.0
Diastolic     78.8   79.666667   50.666667        112.0
Cholesterol  176.0  185.000000  112.000000        350.0
Eigen Values: [6.11590030e+02 5.33446310e+01 5.11057615e-01 2.98761498e+00]
Eigen Vectors:
[[ 0.4384164   0.53943897 -0.64178126 -0.32390348]
 [ 0.44996048  0.43187438  0.76084874 -0.17924641]
 [ 0.2711095   0.24253439 -0.07934997  0.92810575]
 [ 0.72926419 -0.68093112 -0.05412566 -0.03971111]]


In [27]:
#(c) Cholesterol variability 
chol_var = df['Cholesterol'].var()

#Q1
q1 = df['Cholesterol'].quantile(0.25)
#Q3
q3 = df['Cholesterol'].quantile(0.75)
#Interqurtile range 
iqr = q3 - q1
print(f"Cholesterol variability : {chol_var}")
print(f"Q1:{q1}")
print(f"Q3:{q3}")
print(f"Interquartile range:{iqr}")


Cholesterol variability : 350.0
Q1:192.5
Q3:217.5
Interquartile range:25.0


In [29]:
#(d) Detect Pulse anomalies using Z-score
# Z-score = (x - mean) / std
df['Pulse_Zscore'] = (df['Pulse'] - mean_pulse) / std_pulse

print(df[['ID', 'Pulse', 'Pulse_Zscore']])

     ID  Pulse  Pulse_Zscore
0  P001     72     -0.284321
1  P002     85      0.947736
2  P003     60     -1.421604
3  P004     78      0.284321
4  P005     65     -0.947736
5  P006     90      1.421604
